const DEFAULTS={language:'zh',widthMode:'medium',customWidth:1400,backgroundMode:'default',customTone:'#f6f8fb',fontSize:16,lineHeight:1.72,messageEmphasis:false,messageStyle:'soft',messageAccent:'#2f64ff',messageStrength:45,codeWrap:true,popupDark:false,navigatorEnabled:true,exportMode:'current',exportScope:'all',exportStart:1,exportEnd:999,exportIncludeMeta:true,exportIncludeImages:true};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let settings={...DEFAULTS};let scanState='idle';
const MSG={
  zh:{saved:'已保存',openNav:'打开导航',closeNav:'关闭导航',chatNeeded:'请先打开 ChatGPT 对话页',exportFail:'导出失败，请确认当前为 ChatGPT 对话',exportIncomplete:'未能确认已扫描全部聊天内容，本次未执行“全部聊天”导出。请先完成完整扫描后重试',emphasisOn:'已开启用户消息强调',emphasisOff:'已恢复 ChatGPT 原生用户气泡',navOn:'已开启长对话导航',navOff:'已关闭长对话导航',theme:'已切换插件界面主题',pro:'Pro 入口已预留',settings:'当前已在设置界面',pdf:'已打开 PDF 打印窗口',md:'已导出 Markdown',copyMd:'已复制 Markdown',txt:'已导出 TXT',scan:'完整扫描',scanning:'扫描中…',scanStart:'正在前往对话底部并准备完整扫描…',scanDone:'扫描完成',scanFail:'完整扫描失败，请确认当前为 ChatGPT 对话',navOpen:'已打开长对话导航',navClose:'已关闭长对话导航',codeOn:'已开启代码换行',codeOff:'已关闭代码换行',reset:'已恢复默认设置',pauseScan:'暂停扫描',resumeScan:'继续扫描',stopScan:'结束扫描',scanPaused:'扫描已暂停',scanStopped:'扫描已结束',exportBusy:'完整扫描正在进行，请等待扫描完成或先结束扫描',exportPaused:'扫描当前已暂停，请继续扫描或结束扫描后再导出',noContent:'当前没有可导出的聊天内容',saveFail:'设置保存失败，请稍后重试'},
  en:{saved:'Saved',openNav:'Open navigator',closeNav:'Close navigator',chatNeeded:'Open a ChatGPT conversation first',exportFail:'Export failed. Make sure the active tab is a ChatGPT conversation.',exportIncomplete:'The full conversation could not be verified as completely scanned, so the full export was not created. Complete a full scan and try again.',emphasisOn:'User-message emphasis enabled',emphasisOff:'Restored ChatGPT default user messages',navOn:'Long-chat navigator enabled',navOff:'Long-chat navigator disabled',theme:'Extension theme changed',pro:'Pro entry reserved for a future release',settings:'You are already in Settings',pdf:'PDF print view opened',md:'Markdown exported',copyMd:'Markdown copied',txt:'TXT exported',scan:'Full scan',scanning:'Scanning…',scanStart:'Going to the bottom and preparing a full scan…',scanDone:'Scan complete',scanFail:'Full scan failed. Make sure the active tab is a ChatGPT conversation.',navOpen:'Long-chat navigator opened',navClose:'Long-chat navigator closed',codeOn:'Code wrapping enabled',codeOff:'Code wrapping disabled',reset:'Defaults restored',pauseScan:'Pause scan',resumeScan:'Resume scan',stopScan:'Stop scan',scanPaused:'Scan paused',scanStopped:'Scan stopped',exportBusy:'A full scan is currently running. Wait for it to finish or stop it before exporting.',exportPaused:'The scan is paused. Resume or stop it before exporting.',noContent:'There is no conversation content to export.',saveFail:'Failed to save settings. Please try again.'}
};
const STATIC_ZH_EN={
  '导出':'Export','布局':'Layout','阅读':'Reading','用户消息':'Your messages','工具':'Tools','导出 PDF':'Export PDF','导出 Markdown':'Export Markdown','复制 Markdown':'Copy Markdown','导出 TXT':'Export TXT','导出设置':'Export settings','导出模式':'Export mode','当前已显示':'Currently loaded','全部聊天':'Full conversation','自定义':'Custom','导出角色':'Roles','全部问答':'All turns','仅我的问题':'My prompts only','仅 GPT 回答':'GPT replies only','仅书签':'Bookmarks only','从第':'From','问':'Q','到第':'to','包含标题与来源':'Include title and source','保留图片':'Keep images','默认只导出当前页面已经加载出来的对话，不进行自动滚动。选择“全部聊天”或“自定义”时，会先扫描完整聊天内容，再进行导出。':'By default, only conversation content currently loaded on the page is exported, with no automatic scrolling. Full conversation and Custom first scan the whole chat before exporting.','宽度模式':'Width mode','窄':'Narrow','适中':'Medium','宽':'Wide','自定义宽度':'Custom width','页面色调':'Page tone','字体大小':'Font size','行高':'Line height','紧':'Tight','自定义行高':'Custom line height','强调用户消息':'Emphasize my messages','强调样式':'Emphasis style','配色':'Accent','颜色深浅':'Color intensity','代码换行':'Wrap code','恢复默认':'Reset','完整扫描':'Full scan','打开导航':'Open navigator','关闭导航':'Close navigator','长对话导航':'Long-chat navigator','问题目录、搜索、书签、完整扫描；支持已加载图片缩略图':'Outline, search, bookmarks and full scan; loaded images can appear as thumbnails','♡\u00a0 支持 GPT View+':'♡\u00a0 Support GPT View+','有问题联系邮箱：1508925162@qq.com':'Support: 1508925162@qq.com','完成':'Done','暂停扫描':'Pause scan','继续扫描':'Resume scan','结束扫描':'Stop scan'
};
const STATIC_EN_ZH=Object.fromEntries(Object.entries(STATIC_ZH_EN).map(([a,b])=>[b,a]));
function tr(key){return (MSG[settings.language]||MSG.zh)[key]||key;}
const getSettings=()=>new Promise(r=>chrome.storage.sync.get(DEFAULTS,r));
const setSettings=patch=>new Promise((resolve,reject)=>{const previous=Object.fromEntries(Object.keys(patch).map(k=>[k,settings[k]]));settings={...settings,...patch};chrome.storage.sync.set(patch,()=>{const err=chrome.runtime.lastError;if(err){for(const [k,v] of Object.entries(previous))if(settings[k]===patch[k])settings[k]=v;reject(new Error(err.message||'STORAGE_WRITE_FAILED'));}else resolve();});});
let colorSaveTimer=null,colorPending={};
function queueColorSave(patch){settings={...settings,...patch};syncUI();colorPending={...colorPending,...patch};clearTimeout(colorSaveTimer);colorSaveTimer=setTimeout(async()=>{const pending=colorPending;colorPending={};try{await setSettings(pending);}catch(_){toast(tr('saveFail'));}},750);}
async function flushColorSave(){if(!Object.keys(colorPending).length)return;clearTimeout(colorSaveTimer);const pending=colorPending;colorPending={};try{await setSettings(pending);}catch(_){toast(tr('saveFail'));}}
function cancelColorSave(){clearTimeout(colorSaveTimer);colorPending={};}
function flushColorSaveOnUnload(){if(!Object.keys(colorPending).length)return;clearTimeout(colorSaveTimer);const pending=colorPending;colorPending={};try{chrome.storage.sync.set(pending);}catch(_){}}
async function activeTab(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});return tabs[0];}
async function sendAction(action,payload={}){const tab=await activeTab();if(!tab?.id)throw new Error('NO_TAB');return chrome.tabs.sendMessage(tab.id,{action,payload});}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200);}
function setActive(selector,value){$$(selector).forEach(b=>b.classList.toggle('active',String(b.dataset.value)===String(value)));}
function translateStatic(){
  const toEn=settings.language==='en',map=toEn?STATIC_ZH_EN:STATIC_EN_ZH;
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement?.closest('script,style,svg')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});
  const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
  nodes.forEach(n=>{const raw=n.nodeValue,trim=raw.trim();if(!trim||!map[trim])return;const lead=raw.match(/^\s*/)?.[0]||'',tail=raw.match(/\s*$/)?.[0]||'';n.nodeValue=lead+map[trim]+tail;});
  document.documentElement.lang=toEn?'en':'zh-CN';
  $('#languageBtn').textContent=toEn?'中':'EN';$('#languageBtn').title=toEn?'切换到中文':'Switch to English';
}
function exportOptions(){return{mode:['current','all','custom'].includes(settings.exportMode)?settings.exportMode:'current',scope:settings.exportScope,start:Number(settings.exportStart)||1,end:Number(settings.exportEnd)||999,includeMeta:!!settings.exportIncludeMeta,includeImages:!!settings.exportIncludeImages};}
function exportSummary(){const zh=settings.language!=='en';const mode=(zh?{current:'当前已显示内容',all:'全部聊天',custom:'自定义范围'}:{current:'Currently loaded',all:'Full conversation',custom:'Custom range'})[settings.exportMode]||(zh?'当前已显示内容':'Currently loaded');return `${mode} · ${zh?'保留格式':'Keep formatting'}`;}
function syncUI(){settings.customWidth=Math.min(1500,Math.max(900,Number(settings.customWidth)||1400));setActive('.width-btn',settings.widthMode);setActive('.swatch[data-value]',settings.backgroundMode);setActive('.line-btn',settings.lineHeight);setActive('.bubble-style',settings.messageStyle);setActive('.accent[data-value]',settings.messageAccent);setActive('.export-mode',settings.exportMode);$('#customWidth').value=settings.customWidth;$('#customWidthValue').textContent=`${settings.customWidth}px`;$('#customWidthRow').classList.toggle('hidden',settings.widthMode!=='custom');$('#customTone').value=settings.customTone;$('.custom-swatch').classList.toggle('active',settings.backgroundMode==='custom');$('#fontValue').textContent=`${settings.fontSize}px`;$('#lineHeightRange').value=settings.lineHeight;$('#lineHeightValue').textContent=Number(settings.lineHeight).toFixed(2);$('#messageEmphasis').checked=!!settings.messageEmphasis;$('#messageControls').classList.toggle('disabled',!settings.messageEmphasis);$('#customAccent').value=settings.messageAccent;$('#messageStrength').value=settings.messageStrength;$('#messageStrengthValue').textContent=`${settings.messageStrength}%`;$('#navigatorEnabled').checked=!!settings.navigatorEnabled;$('#exportScope').value=settings.exportScope;$('#exportStart').value=settings.exportStart;$('#exportEnd').value=settings.exportEnd;$('#customExportBlock').classList.toggle('active',settings.exportMode==='custom');$('#exportIncludeMeta').checked=!!settings.exportIncludeMeta;$('#exportIncludeImages').checked=!!settings.exportIncludeImages;document.body.classList.toggle('dark',!!settings.popupDark);$('#codeWrapBtn')?.classList.toggle('active',!!settings.codeWrap);translateStatic();$('#exportSummary').textContent=exportSummary();}
function updateSideNav(id){$$('.side-tab').forEach(b=>b.classList.toggle('active',b.dataset.target===id));}
function bindSideNav(){const scroller=$('#contentScroll');$$('.side-tab').forEach(btn=>btn.addEventListener('click',()=>{const el=document.getElementById(btn.dataset.target);if(!el)return;scroller.scrollTo({top:el.offsetTop-4,behavior:'smooth'});updateSideNav(btn.dataset.target);}));let timer;scroller.addEventListener('scroll',()=>{clearTimeout(timer);timer=setTimeout(()=>{const y=scroller.scrollTop+30;let current='section-export';$$('.settings-section').forEach(s=>{if(s.offsetTop<=y)current=s.id;});updateSideNav(current);},45);},{passive:true});}
async function save(patch,msg){try{await setSettings(patch);syncUI();toast(msg||tr('saved'));return true;}catch(_){syncUI();toast(tr('saveFail'));return false;}}
async function doExport(action,successKey){try{const r=await sendAction(action,{export:exportOptions()});if(r?.ok===false)throw new Error(r.error||'EXPORT_FAILED');toast(r?.message||tr(successKey));}catch(e){const m=String(e?.message||'');let msg=tr('exportFail');if(m==='NO_TAB')msg=tr('chatNeeded');else if(m.includes('FULL_SCAN_INCOMPLETE'))msg=tr('exportIncomplete');else if(m.includes('SCAN_PAUSED'))msg=tr('exportPaused');else if(m.includes('SCAN_IN_PROGRESS'))msg=tr('exportBusy');else if(m.includes('NO_EXPORT_CONTENT'))msg=tr('noContent');toast(msg);}}
function setNavigatorButton(open){const label=$('#openNavigator span');if(label)label.textContent=open?tr('closeNav'):tr('openNav');$('#openNavigator').classList.toggle('active',!!open);$('#openNavigator').setAttribute('aria-pressed',open?'true':'false');}
async function refreshNavigatorState(){try{const r=await sendAction('navigator_status');if(r?.ok)setNavigatorButton(!!r.open);else setNavigatorButton(false);}catch(_){setNavigatorButton(false);}}
async function refreshScanState(){try{const r=await sendAction('scan_status');if(!r?.ok||!r.busy){scanState='idle';setScanButtonProgress(100,'','idle');return;}scanState=r.paused?'paused':'running';setScanButtonProgress(Math.max(1,r.percent||1),'',scanState);}catch(_){scanState='idle';setScanButtonProgress(100,'','idle');}}
function setScanButtonProgress(percent,text,state='running'){const btn=$('#fullScanBtn'),label=btn?.querySelector('span');if(!btn||!label)return;scanState=state||scanState;if(percent>=100||state==='idle'||state==='stopped'){scanState='idle';label.textContent=tr('scan');btn.classList.remove('scan-running','scan-paused');btn.disabled=false;if(text)toast(text);return;}btn.disabled=false;btn.classList.toggle('scan-running',scanState==='running');btn.classList.toggle('scan-paused',scanState==='paused');label.textContent=scanState==='paused'?tr('resumeScan'):`${tr('pauseScan')} ${Math.max(0,Math.min(99,Math.round(percent||0)))}%`;if(text&&state==='paused')toast(text);}
chrome.runtime.onMessage.addListener((msg)=>{if(msg?.type==='gpt-view-plus-scan-progress'){setScanButtonProgress(msg.percent,msg.text,msg.state||'running');}});
async function init(){settings=await getSettings();syncUI();bindSideNav();
  $('#languageBtn').addEventListener('click',async()=>{const next=settings.language==='en'?'zh':'en';await setSettings({language:next});settings.language=next;syncUI();await refreshNavigatorState();await refreshScanState();toast(next==='en'?'Switched to English':'已切换为中文');});
  $('#exportConfigToggle').addEventListener('click',(e)=>{e.stopPropagation();$('#exportConfig').classList.toggle('open');});$('#exportConfigDone').addEventListener('click',()=>$('#exportConfig').classList.remove('open'));$('#exportConfig').addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',()=>$('#exportConfig').classList.remove('open'));document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#exportConfig').classList.remove('open');});
  $$('.width-btn').forEach(b=>b.addEventListener('click',()=>save({widthMode:b.dataset.value})));$('#customWidth').addEventListener('input',e=>{$('#customWidthValue').textContent=`${e.target.value}px`;});$('#customWidth').addEventListener('change',e=>save({customWidth:Math.min(1500,Math.max(900,Number(e.target.value)||1400)),widthMode:'custom'}));
  $$('.swatch[data-value]').forEach(b=>b.addEventListener('click',()=>save({backgroundMode:b.dataset.value})));$('#customTone').addEventListener('input',e=>queueColorSave({customTone:e.target.value,backgroundMode:'custom'}));$('#customTone').addEventListener('change',flushColorSave);$$('.line-btn').forEach(b=>b.addEventListener('click',()=>save({lineHeight:Number(b.dataset.value)})));$('#lineHeightRange').addEventListener('input',e=>{$('#lineHeightValue').textContent=Number(e.target.value).toFixed(2);});$('#lineHeightRange').addEventListener('change',e=>save({lineHeight:Number(e.target.value)}));$('#fontMinus').addEventListener('click',()=>save({fontSize:Math.max(14,settings.fontSize-1)}));$('#fontPlus').addEventListener('click',()=>save({fontSize:Math.min(22,settings.fontSize+1)}));
  $('#messageEmphasis').addEventListener('change',e=>save({messageEmphasis:e.target.checked},e.target.checked?tr('emphasisOn'):tr('emphasisOff')));$$('.bubble-style').forEach(b=>b.addEventListener('click',()=>save({messageStyle:b.dataset.value})));$$('.accent[data-value]').forEach(b=>b.addEventListener('click',()=>save({messageAccent:b.dataset.value})));$('#customAccent').addEventListener('input',e=>queueColorSave({messageAccent:e.target.value}));$('#customAccent').addEventListener('change',flushColorSave);$('#messageStrength').addEventListener('input',e=>{$('#messageStrengthValue').textContent=`${e.target.value}%`;});$('#messageStrength').addEventListener('change',e=>save({messageStrength:Number(e.target.value)}));
  $$('.export-mode').forEach(b=>b.addEventListener('click',()=>save({exportMode:b.dataset.value})));$('#exportScope').addEventListener('change',e=>save({exportScope:e.target.value}));$('#exportStart').addEventListener('change',e=>save({exportStart:Math.max(1,Number(e.target.value)||1)}));$('#exportEnd').addEventListener('change',e=>save({exportEnd:Math.max(1,Number(e.target.value)||999)}));$('#exportIncludeMeta').addEventListener('change',e=>save({exportIncludeMeta:e.target.checked}));$('#exportIncludeImages').addEventListener('change',e=>save({exportIncludeImages:e.target.checked}));
  $('#navigatorEnabled').addEventListener('change',async e=>{await save({navigatorEnabled:e.target.checked},e.target.checked?tr('navOn'):tr('navOff'));if(!e.target.checked)setNavigatorButton(false);else await refreshNavigatorState();});$('#themeBtn').addEventListener('click',()=>save({popupDark:!settings.popupDark},tr('theme')));$('#proBtn').addEventListener('click',()=>toast(tr('pro')));$('#settingsBtn').addEventListener('click',()=>toast(tr('settings')));
  $('#exportPdf').addEventListener('click',()=>doExport('export_pdf','pdf'));$('#exportMd').addEventListener('click',()=>doExport('export_md','md'));$('#copyMd').addEventListener('click',()=>doExport('copy_md','copyMd'));$('#exportTxt').addEventListener('click',()=>doExport('export_txt','txt'));
  $('#fullScanBtn').addEventListener('click',async()=>{try{if(scanState==='running'){const r=await sendAction('scan_pause');if(r?.ok===false)throw new Error(r.error||'PAUSE_FAILED');scanState='paused';setScanButtonProgress(r.percent||1,tr('scanPaused'),'paused');return;}if(scanState==='paused'){const r=await sendAction('scan_resume');if(r?.ok===false)throw new Error(r.error||'RESUME_FAILED');scanState='running';setScanButtonProgress(r.percent||1,'','running');return;}scanState='running';setScanButtonProgress(1,tr('scanStart'),'running');const r=await sendAction('full_scan');if(r?.ok===false)throw new Error(r.error||'SCAN_FAILED');toast(r?.message||tr('scanDone'));}catch(e){const m=String(e?.message||'');if(m.includes('NO_CONVERSATION')||m==='NO_TAB')toast(tr('chatNeeded'));else if(m.includes('SCAN_PAUSED'))toast(tr('exportPaused'));else if(m.includes('SCAN_IN_PROGRESS'))toast(tr('exportBusy'));else toast(tr('scanFail'));}finally{if(scanState!=='paused')setScanButtonProgress(100,'','idle');}});
  window.addEventListener('pagehide',flushColorSaveOnUnload,{once:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushColorSaveOnUnload();});
  $('#openNavigator').addEventListener('click',async()=>{try{const r=await sendAction('toggle_navigator');if(r?.ok===false)throw new Error(r.error||'NAV_FAILED');setNavigatorButton(!!r.open);toast(r.open?tr('navOpen'):tr('navClose'));}catch{toast(tr('chatNeeded'));}});$('#codeWrapBtn').addEventListener('click',async()=>{const next=!settings.codeWrap;await save({codeWrap:next},next?tr('codeOn'):tr('codeOff'));});$('#clearBtn').addEventListener('click',async()=>{cancelColorSave();const popupDark=settings.popupDark,language=settings.language;settings={...DEFAULTS,popupDark,language};try{await new Promise((resolve,reject)=>chrome.storage.sync.set(settings,()=>{const err=chrome.runtime.lastError;err?reject(new Error(err.message)):resolve();}));syncUI();toast(tr('reset'));}catch(_){toast(tr('saveFail'));}});await refreshNavigatorState();await refreshScanState();
}
init();
